services:
  mysql:
    image: mysql:8.4
    container_name: loan-engine-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loan_engine
      MYSQL_USER: loan_user
      MYSQL_PASSWORD: loan_pass
    ports:
      - "3306:3306"
    volumes:
      - loan_engine_mysql_data:/var/lib/mysql

volumes:
  loan_engine_mysql_data: