spring.application.name=loan-engine

spring.datasource.url=jdbc:mysql://localhost:3306/loan_engine?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=loan_user
spring.datasource.password=loan_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080